version: "3.8"
volumes:
  postgres_data:
    driver: local

services:
  postgres:
    container_name: scoir_db
    image: scoir_db:v1
    environment:
      POSTGRES_USER: ${PG_USER}
      POSTGRES_PASSWORD: ${PG_PASS}
      PGDATA: /data/postgres
    volumes:
      - postgres_data:/var/lib/postgresql/
    ports:
      - "5444:5432"
    env_file:
      - .env
  test_postgres:
    container_name: scoir_test_db
    image: scoir_db:v1
    environment:
      POSTGRES_USER: ${PG_USER}
      POSTGRES_PASSWORD: ${PG_PASS}
    ports:
      - "5433:5432"
    env_file:
      - .env
